version: '3.4'
services:

  # The Application
  app:
    image: ${CONTAINER_REGISTRY_BASE}/app
    build:
      context: ./app
    environment:
      - APP_ENV=${APP_ENV}
      - XDEBUG_VERSION=${WORKSPACE_XDEBUG_VERSION}
    working_dir: /var/www
    volumes:
      - ./app/assessment_repo/:/var/www:rw,delegated
    env_file: 
      - .env
    depends_on:
      - database 

  # The Web Server
  web:
    image: ${CONTAINER_REGISTRY_BASE}/web
    build:
      context: ./tools/nginx
    working_dir: /var/www
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ./app/assessment_repo/:/var/www:ro,delegated
      - ./tools/nginx/etc/nginx:/etc/nginx:rw,cached
    ports:
      - 80:80
    depends_on:
      - app
    restart: on-failure   
    networks:
      default:
        aliases:
          - ${CONTAINER_REGISTRY_BASE}.local
