FROM php:7.2.5-fpm AS assessment-php

RUN mkdir /usr/share/man/man1

# Laravel minimum required php packages from https://laravel.com/docs/7.x/installation
RUN apt-get update -yqq && apt-get install -yqq \
        libzip-dev \
        openssl \ 
        vim \
        zip \
        && docker-php-ext-configure zip --with-libzip \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/* 

RUN docker-php-ext-install \
        bcmath \
        ctype \
        fileinfo \
        json \
        mbstring \
        pdo \
        tokenizer \
        zip

# Specific config setup and composer
COPY ./php/conf.d /usr/local/etc/php/conf.d
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY ./scripts/utils.sh /usr/local/bin/my-utils.sh
RUN chmod +x /usr/local/bin/my-utils.sh

# Entrypoint
COPY ./docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]

CMD ["php-fpm"]
